webav_planningyear:
    pattern:  /Planning/{year}
    defaults: { _controller: WebAvPlanningBundle:Default:index }

webav_planning:
    pattern:  /
    defaults: { _controller: WebAvPlanningBundle:Default:accueil }